# Generated by Django 5.1.3 on 2024-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_newslettersubscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='classification',
            field=models.CharField(default='Practitioner', max_length=100),
        ),
    ]
